// Generated by trokky CLI
// Do not edit manually.

export interface BaseDocument {
  _id: string
  _type: string
  _createdAt?: string
  _updatedAt?: string
  _version?: number
  _status?: 'draft' | 'published'
}

export interface MediaAssetReference {
  _ref: string
  _type: 'mediaAsset'
}

export interface MediaFieldValue {
  _type: 'media'
  asset: MediaAssetReference
  alt?: string
  caption?: string
  title?: string
  variant?: string
}

export interface RichTextValue {
  type: 'doc'
  content?: unknown[]
}

export interface Reference<T extends string = string> {
  _ref: string
  _type: T
}

/**
 * Article
 * Blog articles with rich content and metadata
 * Type: document
 */
export interface ArticleDocument extends BaseDocument {
  _type: 'article'
  title: string
  slug: string
  excerpt?: string
  category?: Reference<'category'> | CategoryDocument
  content: RichTextValue
  featured?: boolean
  publishedAt?: string
}

/**
 * Category
 * Article categories
 * Type: document
 */
export interface CategoryDocument extends BaseDocument {
  _type: 'category'
  name: string
  description?: string
  order?: number
}

export type DocumentType = 'article' | 'category'

export type AnyDocument = ArticleDocument | CategoryDocument

export interface DocumentTypeMap {
  'article': ArticleDocument
  'category': CategoryDocument
}

export type DocumentOf<T extends DocumentType> = DocumentTypeMap[T]
