// Generated by trokky CLI
// Do not edit manually.

export interface BaseDocument {
  _id: string
  _type: string
  _createdAt?: string
  _updatedAt?: string
  _version?: number
  _status?: 'draft' | 'published'
}

export interface MediaAssetReference {
  _ref: string
  _type: 'mediaAsset'
}

export interface MediaFieldValue {
  _type: 'media'
  asset: MediaAssetReference
  alt?: string
  caption?: string
  title?: string
  variant?: string
}

export interface Reference<T extends string = string> {
  _ref: string
  _type: T
}

export interface HomePageHeroCta {
  label?: string
  href?: string
}

export interface HomePageHero {
  heading: string
  image?: MediaFieldValue | null
  cta?: HomePageHeroCta
}

export interface HomePageBlocksItem {
  title: string
  body?: string
}

/**
 * Home Page
 * Legacy array-form schema for the landing page
 * Type: document
 */
export interface HomePageDocument extends BaseDocument {
  _type: 'home-page'
  hero: HomePageHero
  tags?: string[]
  blocks?: HomePageBlocksItem[]
  gallery?: unknown[]
  cover?: MediaFieldValue | null
  'hero-image'?: MediaFieldValue | null
  related?: Reference<'category' | 'author'> | CategoryDocument
  legacyOwner?: Reference<'author'>
  weird?: unknown
}

/**
 * Category
 * Article categories
 * Type: document
 */
export interface CategoryDocument extends BaseDocument {
  _type: 'category'
  name: string
  description?: string
  order?: number
}

export type DocumentType = 'home-page' | 'category'

export type AnyDocument = HomePageDocument | CategoryDocument

export interface DocumentTypeMap {
  'home-page': HomePageDocument
  'category': CategoryDocument
}

export type DocumentOf<T extends DocumentType> = DocumentTypeMap[T]
