// Generated by trokky CLI
// Do not edit manually.

export interface BaseDocument {
  _id: string
  _type: string
  _createdAt?: string
  _updatedAt?: string
  _version?: number
  _status?: 'draft' | 'published'
}

export interface MediaAssetReference {
  _ref: string
  _type: 'mediaAsset'
}

export interface MediaFieldValue {
  _type: 'media'
  asset: MediaAssetReference
  alt?: string
  caption?: string
  title?: string
  variant?: string
}

export interface Reference<T extends string = string> {
  _ref: string
  _type: T
}

/**
 * Site Settings
 * Global site configuration
 * Type: singleton
 */
export interface SiteSettingsDocument extends BaseDocument {
  _type: 'siteSettings'
  siteTitle: string
  logo?: MediaFieldValue | null
  maintenance?: boolean
  theme?: unknown
  launchedAt?: string
}

export type DocumentType = 'siteSettings'

export type AnyDocument = SiteSettingsDocument

export interface DocumentTypeMap {
  'siteSettings': SiteSettingsDocument
}

export type DocumentOf<T extends DocumentType> = DocumentTypeMap[T]
