package client

import (
	"encoding/json"
	"flag"
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

var updateGolden = flag.Bool("update", false, "rewrite testdata/*.golden.ts from generator output")

func loadSchema(t *testing.T, file string) Schema {
	t.Helper()
	raw, err := os.ReadFile(filepath.Join("testdata", file))
	if err != nil {
		t.Fatalf("read fixture %s: %v", file, err)
	}
	schema, err := parseSchema(raw)
	if err != nil {
		t.Fatalf("parse fixture %s: %v", file, err)
	}
	return schema
}

func loadSchemas(t *testing.T, files ...string) []Schema {
	t.Helper()
	schemas := make([]Schema, 0, len(files))
	for _, f := range files {
		schemas = append(schemas, loadSchema(t, f))
	}
	return schemas
}

// --- GenerateTypeScript() ---

func TestGenerateTypeScript(t *testing.T) {
	tests := []struct {
		name     string
		fixtures []string
		golden   string
		contains []string
		absent   []string
	}{
		{
			name:     "record form article",
			fixtures: []string{"schema_article.json", "schema_category.json"},
			golden:   "article.golden.ts",
			contains: []string{
				"export interface ArticleDocument extends BaseDocument {",
				"  _type: 'article'",
				"  title: string",
				"  slug: string",
				"  excerpt?: string",
				"  category?: Reference<'category'> | CategoryDocument",
				"  content: RichTextValue",
				"  featured?: boolean",
				"  publishedAt?: string",
				"export interface CategoryDocument extends BaseDocument {",
				"  order?: number",
				" * Blog articles with rich content and metadata",
			},
		},
		{
			name:     "legacy array form",
			fixtures: []string{"schema_home_page.json", "schema_category.json"},
			golden:   "legacy.golden.ts",
			contains: []string{
				"export interface HomePageHeroCta {",
				"export interface HomePageHero {",
				"export interface HomePageBlocksItem {",
				"export interface HomePageDocument extends BaseDocument {",
				"  _type: 'home-page'",
				"  hero: HomePageHero",
				"  cta?: HomePageHeroCta",
				"  tags?: string[]",
				"  blocks?: HomePageBlocksItem[]",
				"  gallery?: unknown[]",
				"  cover?: MediaFieldValue | null",
				"  'hero-image'?: MediaFieldValue | null",
				"  related?: Reference<'category' | 'author'> | CategoryDocument",
				"  legacyOwner?: Reference<'author'>",
				"  weird?: unknown",
			},
			absent: []string{
				"AuthorDocument",
			},
		},
		{
			name:     "singleton",
			fixtures: []string{"schema_settings.json"},
			golden:   "singleton.golden.ts",
			contains: []string{
				" * Type: singleton",
				"export interface SiteSettingsDocument extends BaseDocument {",
				"  _type: 'siteSettings'",
				"  siteTitle: string",
				"  logo?: MediaFieldValue | null",
				"  maintenance?: boolean",
				"  theme?: unknown",
				"  launchedAt?: string",
				"export type DocumentType = 'siteSettings'",
				"  'siteSettings': SiteSettingsDocument",
			},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			out := GenerateTypeScript(loadSchemas(t, tt.fixtures...))

			// Shared preamble is always present and self-contained.
			for _, want := range []string{
				"// Generated by trokky CLI",
				"export interface BaseDocument {",
				"  _id: string",
				"  _status?: 'draft' | 'published'",
				"export interface MediaAssetReference {",
				"export interface MediaFieldValue {",
				"export interface Reference<T extends string = string> {",
				"export interface DocumentTypeMap {",
				"export type DocumentOf<T extends DocumentType> = DocumentTypeMap[T]",
			} {
				if !strings.Contains(out, want) {
					t.Errorf("output missing %q", want)
				}
			}
			if strings.Contains(out, "import ") {
				t.Error("output must not import anything")
			}

			for _, want := range tt.contains {
				if !strings.Contains(out, want+"\n") {
					t.Errorf("output missing line %q", want)
				}
			}
			for _, unwanted := range tt.absent {
				if strings.Contains(out, unwanted) {
					t.Errorf("output unexpectedly contains %q", unwanted)
				}
			}

			// DocumentTypeMap has one entry per collection.
			for _, s := range loadSchemas(t, tt.fixtures...) {
				entry := "  '" + s.Name + "': " + pascalCase(s.Name) + "Document\n"
				if !strings.Contains(out, entry) {
					t.Errorf("DocumentTypeMap missing entry %q", strings.TrimSpace(entry))
				}
			}

			goldenPath := filepath.Join("testdata", tt.golden)
			if *updateGolden {
				if err := os.WriteFile(goldenPath, []byte(out), 0644); err != nil {
					t.Fatalf("write golden: %v", err)
				}
				return
			}
			want, err := os.ReadFile(goldenPath)
			if err != nil {
				t.Fatalf("read golden (run with -update to create): %v", err)
			}
			if string(want) != out {
				t.Errorf("output does not match %s\n--- got ---\n%s", tt.golden, out)
			}
		})
	}
}

func TestGenerateTypeScript_Empty(t *testing.T) {
	out := GenerateTypeScript(nil)
	for _, want := range []string{
		"export type DocumentType = never",
		"export type AnyDocument = never",
		"export interface DocumentTypeMap {",
		"export interface BaseDocument {",
	} {
		if !strings.Contains(out, want) {
			t.Errorf("output missing %q", want)
		}
	}
}

func TestGenerateTypeScript_UnknownTypesBecomeUnknown(t *testing.T) {
	schemas := []Schema{{
		Name:  "widget",
		Title: "Widget",
		Type:  "document",
		Fields: []Field{
			{Name: "custom", Type: "myCustomField"},
			{Name: "nothing", Type: ""},
			{Name: "list", Type: "array"},
		},
	}}

	out := GenerateTypeScript(schemas)
	for _, want := range []string{
		"  custom?: unknown\n",
		"  nothing?: unknown\n",
		"  list?: unknown[]\n",
	} {
		if !strings.Contains(out, want) {
			t.Errorf("output missing %q", want)
		}
	}
}

func TestPascalCase(t *testing.T) {
	cases := map[string]string{
		"article":     "Article",
		"home-page":   "HomePage",
		"blogPost":    "BlogPost",
		"site_config": "SiteConfig",
		"page2":       "Page2",
		"2cool":       "_2cool",
		"":            "Unnamed",
	}
	for in, want := range cases {
		if got := pascalCase(in); got != want {
			t.Errorf("pascalCase(%q) = %q, want %q", in, got, want)
		}
	}
}

func TestPropertyName(t *testing.T) {
	cases := map[string]string{
		"title":      "title",
		"hero-image": "'hero-image'",
		"_id":        "_id",
		"2cool":      "'2cool'",
	}
	for in, want := range cases {
		if got := propertyName(in); got != want {
			t.Errorf("propertyName(%q) = %q, want %q", in, got, want)
		}
	}
}

func TestParseFields_PreservesRecordOrder(t *testing.T) {
	raw := []byte(`{"name":"ordered","fields":{"zeta":{"type":"string"},"alpha":{"type":"string"},"mid":{"type":"string"},"beta":{"type":"string"}}}`)
	schema, err := parseSchema(raw)
	if err != nil {
		t.Fatalf("parseSchema: %v", err)
	}
	want := []string{"zeta", "alpha", "mid", "beta"}
	if len(schema.Fields) != len(want) {
		t.Fatalf("got %d fields, want %d", len(schema.Fields), len(want))
	}
	for i, name := range want {
		if schema.Fields[i].Name != name {
			t.Fatalf("field %d = %q, want %q", i, schema.Fields[i].Name, name)
		}
	}
}

// --- GenerateTypes() over HTTP ---

func serveSchemas(t *testing.T, names []string, fixtures map[string]string) (*Client, *[]string) {
	t.Helper()

	var paths []string
	server := newTestServer(t, func(w http.ResponseWriter, r *http.Request) {
		paths = append(paths, r.URL.Path)

		if r.URL.Path == "/collections" {
			collections := make([]map[string]string, 0, len(names))
			for _, n := range names {
				collections = append(collections, map[string]string{"name": n})
			}
			apiSuccess(w, map[string]interface{}{"collections": collections})
			return
		}

		name := strings.TrimPrefix(r.URL.Path, "/schemas/")
		fixture, ok := fixtures[name]
		if !ok {
			apiError(w, 404, "schema not found")
			return
		}
		raw, err := os.ReadFile(filepath.Join("testdata", fixture))
		if err != nil {
			t.Errorf("read fixture: %v", err)
			apiError(w, 500, "fixture error")
			return
		}
		apiSuccess(w, map[string]interface{}{"schema": json.RawMessage(raw)})
	})

	return New(server.URL, "token"), &paths
}

func TestGenerateTypes_Success(t *testing.T) {
	c, paths := serveSchemas(t,
		[]string{"article", "category", "home-page"},
		map[string]string{
			"article":   "schema_article.json",
			"category":  "schema_category.json",
			"home-page": "schema_home_page.json",
		})

	out, err := c.GenerateTypes()
	if err != nil {
		t.Fatalf("GenerateTypes() error: %v", err)
	}

	wantPaths := []string{"/collections", "/schemas/article", "/schemas/category", "/schemas/home-page"}
	if strings.Join(*paths, ",") != strings.Join(wantPaths, ",") {
		t.Fatalf("request paths = %v, want %v", *paths, wantPaths)
	}

	for _, want := range []string{
		"// Generated by trokky CLI",
		"// Source: " + c.BaseURL,
		"export interface ArticleDocument extends BaseDocument {",
		"export interface CategoryDocument extends BaseDocument {",
		"export interface HomePageDocument extends BaseDocument {",
		"  category?: Reference<'category'> | CategoryDocument",
		"export type DocumentType = 'article' | 'category' | 'home-page'",
	} {
		if !strings.Contains(out, want) {
			t.Errorf("output missing %q", want)
		}
	}
}

func TestGenerateTypes_SchemaNotFound(t *testing.T) {
	c, _ := serveSchemas(t, []string{"x"}, map[string]string{})

	_, err := c.GenerateTypes()
	if err == nil {
		t.Fatal("expected error when /schemas/x returns 404")
	}
	if !strings.Contains(err.Error(), "x") {
		t.Fatalf("expected collection name in error, got %q", err.Error())
	}
}

func TestGenerateTypes_CollectionsUnauthorized(t *testing.T) {
	var paths []string
	server := newTestServer(t, func(w http.ResponseWriter, r *http.Request) {
		paths = append(paths, r.URL.Path)
		apiError(w, 401, "not authorized")
	})

	c := New(server.URL, "token")
	if _, err := c.GenerateTypes(); err == nil {
		t.Fatal("expected error on 401")
	}
	if len(paths) != 1 || paths[0] != "/collections" {
		t.Fatalf("expected only /collections request, got %v", paths)
	}
}

func TestParseCollectionNames(t *testing.T) {
	tests := []struct {
		name string
		in   string
		want []string
	}{
		{"wrapped objects", `{"collections":[{"name":"a"},{"name":"b"}]}`, []string{"a", "b"}},
		{"wrapped names", `{"collections":["a","b"]}`, []string{"a", "b"}},
		{"bare objects", `[{"name":"a"}]`, []string{"a"}},
		{"bare names", `["a","b"]`, []string{"a", "b"}},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got, err := parseCollectionNames([]byte(tt.in))
			if err != nil {
				t.Fatalf("parseCollectionNames: %v", err)
			}
			if strings.Join(got, ",") != strings.Join(tt.want, ",") {
				t.Fatalf("got %v, want %v", got, tt.want)
			}
		})
	}

	if _, err := parseCollectionNames([]byte(`{"nope":1}`)); err == nil {
		t.Fatal("expected error for unrecognized format")
	}
}

func TestParseSchema_BareObject(t *testing.T) {
	schema, err := parseSchema([]byte(`{"name":"post","fields":{"title":{"type":"string","required":true}}}`))
	if err != nil {
		t.Fatalf("parseSchema: %v", err)
	}
	if schema.Name != "post" || len(schema.Fields) != 1 || !schema.Fields[0].Required {
		t.Fatalf("unexpected schema: %+v", schema)
	}
}
